architect:
- jachinte
decrypt:
  settings.xml: "repo/.rultor/settings.xml.asc"
  pubring.gpg: "repo/.rultor/pubring.gpg.asc"
  secring.gpg: "repo/.rultor/secring.gpg.asc"
env:
  MAVEN_OPTS: "-Xmx512m -XX:MaxPermSize=256m"
install:
  - mvn validate -Pmissing-dependencies
release:
  script: |
    mvn org.eclipse.tycho:tycho-versions-plugin:set-version "-DnewVersion=${tag}"
    git commit -am "${tag}"
    mvn clean deploy -PPascani --settings /home/r/settings.xml
merge:
  script: |
    mvn clean install
deploy:
  script: |
    mvn clean deploy
