architect:
- jachinte
decrypt:
  settings.xml: "repo/settings.xml.asc"
  pubring.gpg: "repo/pubring.gpg.asc"
  secring.gpg: "repo/secring.gpg.asc"
env:
  MAVEN_OPTS: "-Xmx512m -XX:MaxPermSize=256m"
release:
  script: |
    mvn versions:set "-DnewVersion=${tag}"
    git commit -am "${tag}"
    mvn clean deploy -Pjcabi --settings /home/r/settings.xml
merge:
  script:
    - "mvn clean install"
deploy:
  script:
    - "mvn clean deploy"
